[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"