[build]
  functions = "netlify/functions"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200